- hosts: devserver
  become: true
  
  tasks:
    - name: check to see if pip is already installed
      command: "pip --version"
      ignore_errors: true
      register: pip_is_installed
      changed_when: false
    
    - block:

        - name: download get-pip.py
          get_url: url=https://bootstrap.pypa.io/get-pip.py  dest=/tmp
    
        - name: install pip
          command: "python /tmp/get-pip.py"
    
        - name: delete get-pip.py
          file: state=absent path=/tmp/get-pip.py

      when: pip_is_installed.rc != 0
    
    - name: pip install docker-py>=1.7.0
      pip:
         name: docker-py
         version: "1.7.0"
    
    - name: remove devops demo container
      docker:
        name : DevOPS_Demo_Delete
        image: 192.168.174.133:5000/gs-spring-boot-docker
        state: absent
 
    - name: devops demo container
      docker:
        name: DevOPS_Demo
        image: 192.168.174.133:5000/gs-spring-boot-docker
        pull: always
        insecure_registry: true
        state: reloaded
        ports:
          - "8484:8484"
        expose:
          - 8484
